sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lbrulhart/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lbrulhart/docker-react npm run test

